version: "3.9"

services:
  backend:
    build: ./backend
    container_name: tiry-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    container_name: tiry-frontend
    build:
      context: ./frontend/fleet_management
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/fleet_management:/app       # Mount your source code
      - node_modules:/app/node_modules         # Keep container's node_modules

volumes:
  node_modules: